name: $(year:yyyy).$(Month).$(DayOfMonth)$(rev:.r)
trigger: none

stages:
  - stage: Deploy_Application
    displayName: 'Deploy Application'
    variables:
      az_region: eastus
      resource_group_name: emirates-dnata
      serviceconnection: ednatasp
      subscription: 'Visual Studio Enterprise'
      kubernetesCluster: emiratesdnatak8s
      subscriptionid: f83d6612-187a-4680-bd9a-029b77f35af3
      key_vault_name: ednatakv
      sa_prefix: ednatastorage
      sa_container_name: ednatablob

    jobs:
    - job: Deploy_Kubernetes_Cluster
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: KubectlInstaller@0
        displayName: Kubectl installer
        inputs: 
          kubectlVersion: latest
      - task: Bash@3
        displayName: Display Variables
        inputs:
          name: 'Display_Variables'
          targetType: 'inline'
          script: |
            echo "SubscriptionID = '$(subscriptionid)'."
            echo "Resource Group = '$(resource_group_name)'."
            echo "Kubernetes cluster name = '$(kubernetesCluster)'."
      # - powershell: |
      #     az login --identity
      #     az account set --subscription $(subscriptionid)
      #     az aks get-credentials --resource-group $(resource_group_name) --name $(kubernetesCluster)
      #     kubectl apply -f applications.yml
      - task: Kubernetes@1
        displayName: kubectl apply 
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: ednatasp
          azureResourceGroup: $(resource_group_name)
          kubernetesCluster: $(kubernetesCluster)
          namespace: default
          command: apply
          configurationType: 'configuration'
          configuration: $(System.DefaultWorkingDirectory)
          arguments: -f applications.yml