name: $(year:yyyy).$(Month).$(DayOfMonth)$(rev:.r)
trigger:
- main
stages:
  - stage: Deploy_Cluster
    displayName: 'Deploy Kubernetes Cluster'
    jobs:
    - job: terraform_deployment
      pool:
        vmImage: ubuntu-latest
      variables:
        az_region: eastus
        resource_group_name: emirates-dnata
        serviceconnection: ednatasp
        subscription: 'Visual Studio Enterprise'
        key_vault_name: ednatakv
        sa_prefix: ednatastorage
        sa_container_name: ednatablob
        tfstateFile: terraform.tfstate

      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'ednatasp'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            VAULT_ID=$(az keyvault create --name "$(key_vault_name)" --resource-group "$(resource_group_name)" --location "$(az_region)" --query "id" -o tsv)
            az storage account create --resource-group $(resource_group_name) --name "$(sa_prefix)" --sku Standard_LRS --encryption-services blob
            az storage container create --name $(sa_container_name) --account-name "$(sa_prefix)" --auth-mode login
      - task: TerraformInstaller@0
        displayName: Terraform Installation
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV3@3
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
          backendServiceArm: 'ednatasp'
          backendAzureRmResourceGroupName: '$(resource_group_name)'
          backendAzureRmStorageAccountName: '$(sa_prefix)'
          backendAzureRmContainerName: '$(sa_container_name)'
          backendAzureRmKey: '$(tfstateFile)'

      - task: TerraformTaskV3@3
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
          commandOptions: '-out=tfplan'
          environmentServiceNameAzureRM: 'ednatasp'

      - task: TerraformTaskV3@3
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tf-files'
          commandOptions: 'tfplan'
          environmentServiceNameAzureRM: 'ednatasp'

